name: scp files
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: .
        remote: /appserver/apps/visualiser
        host: ${{ secrets.SERVER2HOST }}
        username: ${{ secrets.SERVER2SSH_USER }}
        password: ${{ secrets.SERVER2PASSWORD }}
